# Generated by Django 5.1.3 on 2024-11-12 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
